### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by wwwYoung** [markWZX/wmd4j#1]
你这份代码中有些地方我不是很明白，可以请教您一下吗

**Comment by markWZX** [comment]
@wwwYoung 请问有什么问题，能否指出来？代码写的比较久了，我会尽力回答。

**Comment by wwwYoung** [comment]
private static final int REMOVE_NODE_FLAG = -1;
	private static final double MULT_FACTOR = 1000000;
这两个变量的作用是什么呢，看的不是很明白，MULT_FACTOR这个我理解的是做归一化的量。
还有就是emd算法部分的大概思路您还记得吗？我看了论文但是觉得您这个代码不是按照论文中的思路来写的。我也是刚接触nlp不久所以很多地方都是一知半解，非常谢谢您能抽空解答我的问题！

**Comment by markWZX** [comment]
十分抱歉，这个代码重点只是实现了[From word embeddings to document distances](http://proceedings.mlr.press/v37/kusnerb15.pdf)中的WMD距离的计算。EMD算法只是我找的一个Java版的解决方案，并没有深入研究，这算法本身只是一个线性规划中的运输问题最优解，并不是nlp领域比较关注的问题，只是正好可以在这个具体的NLP应用上使用。我参考采用了[JFastEMD](https://github.com/telmomenezes/JFastEMD)，如果您想深入了解这份具体代码，不妨去这个repo提issue。
另外，我也没关注这方面了，那篇文章的作者也有后续研究，[Supervised Word Mover’s Distance](http://papers.nips.cc/paper/6139-supervised-word-movers-distance.pdf)，如有兴趣，您也可以看看。

**Comment by wwwYoung** [comment]
谢谢，还有一个问题是你封装的Word2VecUtils中给了三个加载词向量模型的方法，其中分别是指的是什么呢，google词向量是指的python训练出来的词向量模型吗？

**Comment by markWZX** [comment]
`loadWordVector(File file)  //DL4J 0.7版本的训练得到的结果，准确的说是一个压缩包，里面放置了部分训练参数及最终的词向量，以用于增量训练，可能现在0.9版本已经又不一样了`
`loadTxtWordVector(File file)  //DL4J 0.7以前版本的训练得到的结果，一个txt文件`
`loadGoogleWordVector(File file,boolean binary)  //wordvec c++版本程序训练的结果，Google官方给了一个，googlenews-vecctors-negative300.bin，网上有`
